name: Publishable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dry_run:
    name: Dry run publish on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: k-paxian/dart-package-publisher@v1.3
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          dryRunOnly: true
          flutter: true
          skipTests: true
